from __future__ import annotations


ICEBERG_MIN_LAYERS = 7
ICEBERG_MAX_LAYERS = 10
ICEBERG_DEFAULT_LAYERS = ICEBERG_MIN_LAYERS
ICEBERG_TEMPLATE_TIER_COUNT = 10
ICEBERG_TEMPLATE_FILENAME = "icebergtemplate.png"
ICEBERG_TITLE_MAX_LENGTH = 40

MAX_TEXT_ITEMS_PER_LAYER = 10
MAX_IMAGE_ITEMS_PER_LAYER = 4
